version: '3'

services:

  ai-image-generator:
    build: .
    container_name: aiImageGenerator
    restart: always
    ports:
      - "3001:3000"
    environment:
      - AI_IMAGE_GENERATOR_PORT=3000
      - AI_IMAGE_GENERATOR_SAVE_IMAGES=true
      - AI_IMAGE_GENERATOR_OUTPUT_PATH=/app/images
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - OPEN_AI_ORG_ID=${OPEN_AI_ORG_ID}
      - AUTH_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
    volumes:
      - "./../ai-images:/app/images"

